name: Microblocks
version: 2.0
description: Extra building blocks and player heads.
author: itsCrafted

main: net.itscrafted.microblocks.Microblocks
 
commands:
  microblocks:
    description: Spawn microblocks.
    aliases: [mb, miniblocks, micro]
  skull:
    description: Spawn a player skull.
    aliases: [head, playerhead]
  givemb:
    description: Give another player a Microblock.
    aliases: [gmb, mbgive, givemicroblock]
